server:
  port: 8090
  
spring:
  cloud:
    gateway:
      globalcors:
           corsConfigurations:
             '[/**]':
               allowedOrigins:
                 - http://localhost:8080
                 - http://127.0.0.1:8080
               allowedMethods:
                 - GET
      routes:
        - id: route1
          uri: http://localhost:8091/
          predicates:
            - Path=/resource1/**
          filters:
            - SetPath=/resourceserver01/  
        - id: route2
          uri: http://localhost:8092/
          predicates:
            - Path=/resource2/**
          filters:
            - SetPath=/resourceserver02/